import '../geometry/point.dart';
import 'extruder.dart';
import '../slicer/flow.dart';
import '../slicer/toolpath.dart';

class GCodePrintSettings {
  const GCodePrintSettings({
    this.nozzleTemperature = 220,
    this.bedTemperature = 60,
    this.filamentDiameter = 1.75,
    this.lineWidth = 0.42,
    this.layerHeight = 0.2,
    this.nozzleDiameter = 0.4,
    this.travelSpeedMmPerSecond = 150,
    this.perimeterSpeedMmPerSecond = 45,
    this.infillSpeedMmPerSecond = 80,
    this.flowMultiplier = 1,
  });

  final double nozzleTemperature;
  final double bedTemperature;
  final double filamentDiameter;
  final double lineWidth;
  final double layerHeight;
  final double nozzleDiameter;
  final double travelSpeedMmPerSecond;
  final double perimeterSpeedMmPerSecond;
  final double infillSpeedMmPerSecond;
  final double flowMultiplier;
}

/// Minimal deterministic G-code writer for the pure-Dart basic toolpath.
///
/// This remains a migration foundation rather than the final source-equivalent
/// GCode pipeline. Its bead cross-section calculation uses source `Flow.cpp`
/// and E/mm3 conversion uses the source `Extruder.cpp` formula. Machine start /
/// end templates, roles, retraction, acceleration, cooling and the native
/// GCode state machine remain explicitly pending.
class GCodeWriter {
  const GCodeWriter();

  String write(
    ToolpathPlan plan, {
    GCodePrintSettings settings = const GCodePrintSettings(),
  }) {
    if (settings.filamentDiameter <= 0 ||
        settings.lineWidth <= 0 ||
        settings.layerHeight <= 0 ||
        settings.nozzleDiameter <= 0) {
      throw ArgumentError(
        'filamentDiameter, lineWidth, layerHeight and nozzleDiameter must be > 0',
      );
    }

    final out = StringBuffer()
      ..writeln('; generated by Qidi Flow Flutter/Dart basic toolpath pipeline')
      ..writeln('G90 ; absolute XYZ')
      ..writeln('M83 ; relative extrusion')
      ..writeln('M140 S${_number(settings.bedTemperature)}')
      ..writeln('M104 S${_number(settings.nozzleTemperature)}')
      ..writeln('M190 S${_number(settings.bedTemperature)}')
      ..writeln('M109 S${_number(settings.nozzleTemperature)}');

    Point2? current;
    var currentZ = double.nan;
    for (var layerIndex = 0; layerIndex < plan.layers.length; layerIndex++) {
      final layer = plan.layers[layerIndex];
      out.writeln(';LAYER:$layerIndex');
      if (currentZ.isNaN || (layer.z - currentZ).abs() > 1e-9) {
        out.writeln(
          'G0 Z${_number(layer.z)} F${_feed(settings.travelSpeedMmPerSecond)}',
        );
        currentZ = layer.z;
      }

      for (final path in layer.paths) {
        if (path.points.length < 2) continue;
        final start = path.points.first;
        if (current == null || current.distanceTo(start) > 1e-7) {
          out.writeln(
            'G0 X${_number(start.x)} Y${_number(start.y)} '
            'F${_feed(settings.travelSpeedMmPerSecond)}',
          );
          current = start;
        }
        out.writeln(
          path.kind == ToolpathKind.perimeter
              ? ';TYPE:WALL-OUTER'
              : ';TYPE:FILL',
        );

        final pointCount = path.closed ? path.points.length + 1 : path.points.length;
        for (var i = 1; i < pointCount; i++) {
          final next = path.points[i % path.points.length];
          final distance = current!.distanceTo(next);
          if (distance <= 1e-9) continue;
          final extrusion = _extrusionForDistance(distance, settings);
          final speed = path.kind == ToolpathKind.perimeter
              ? settings.perimeterSpeedMmPerSecond
              : settings.infillSpeedMmPerSecond;
          out.writeln(
            'G1 X${_number(next.x)} Y${_number(next.y)} '
            'E${_number(extrusion, decimals: 5)} F${_feed(speed)}',
          );
          current = next;
        }
      }
    }

    out
      ..writeln('M104 S0')
      ..writeln('M140 S0')
      ..writeln('M84');
    return out.toString();
  }

  double _extrusionForDistance(
    double distance,
    GCodePrintSettings settings,
  ) {
    final flow = Flow.nonBridging(
      width: settings.lineWidth,
      height: settings.layerHeight,
      nozzleDiameter: settings.nozzleDiameter,
    );
    final ePerMm3 = ExtruderState.ePerMm3For(
      filamentDiameter: settings.filamentDiameter,
      filamentFlowRatio: settings.flowMultiplier,
    );
    return distance * flow.mm3PerMm * ePerMm3;
  }

  int _feed(double mmPerSecond) => (mmPerSecond * 60).round();

  String _number(double value, {int decimals = 3}) {
    var text = value.toStringAsFixed(decimals);
    text = text.replaceFirst(RegExp(r'\.?0+$'), '');
    return text == '-0' ? '0' : text;
  }
}
